import OpenAI from "openai";

/**
 * Groq serves an OpenAI-compatible API, so the `openai` SDK talks to it
 * unchanged apart from the base URL — no second client library.
 */
const GROQ_BASE_URL = "https://api.groq.com/openai/v1";

/**
 * The one model the app uses. `openai/gpt-oss-20b` is the cheapest text model
 * this Groq account has access to that supports `response_format: json_object`,
 * which every call site depends on. The Llama models named in Groq's public
 * docs return 404 on this key.
 */
export const AI_MODEL = "openai/gpt-oss-20b";

/**
 * `gpt-oss-20b` is a reasoning model: its hidden reasoning tokens are billed
 * against `max_completion_tokens` alongside the visible JSON, so budgets here
 * run several times larger than the same prompt needed on GPT-4o.
 */
export const AI_MAX_COMPLETION_TOKENS = 800;

export function createAIClient(): OpenAI {
  return new OpenAI({
    apiKey: process.env.GROQ_API_KEY!,
    baseURL: GROQ_BASE_URL,
  });
}

/**
 * `json_object` mode only asks the model for JSON — it can still emit malformed
 * output, which Groq rejects with a 400 `json_validate_failed` (observed
 * intermittently on the resume-generation prompt). A `json_schema` constrains
 * decoding instead, so the shape is guaranteed rather than requested.
 */
export function jsonSchemaFormat(name: string, schema: Record<string, unknown>) {
  return {
    type: "json_schema" as const,
    json_schema: { name, schema, strict: true },
  };
}

/** Shorthands for the schema fragments every call site repeats. */
export const AI_STRING = { type: "string" } as const;
export const AI_STRING_ARRAY = { type: "array", items: { type: "string" } } as const;

/** Strict mode requires every property listed in `required`. */
export function aiObject(properties: Record<string, unknown>) {
  return {
    type: "object",
    properties,
    required: Object.keys(properties),
    additionalProperties: false,
  };
}

/**
 * The 9-field company dossier is a far larger answer than a match score, and
 * every hidden reasoning token is billed against the same budget — 800 truncates
 * it mid-JSON.
 */
export const AI_MAX_COMPLETION_TOKENS_RESEARCH = 3000;

/** Stagehand's page extraction sends a whole accessibility tree and wants JSON back. */
export const AI_MAX_COMPLETION_TOKENS_BROWSER = 4000;

type LLMTextBlock = { type: "text"; text: string };
type LLMBlock = LLMTextBlock | { type: string; [key: string]: unknown };

/** Stagehand messages carry either one content block or an array of them. */
function blocksToText(content: LLMBlock | LLMBlock[]): string {
  const blocks = Array.isArray(content) ? content : [content];
  return blocks
    .map((block) => {
      if (block.type === "text") {
        return (block as LLMTextBlock).text;
      }
      // gpt-oss-20b is text-only, so an image block has no representation to
      // send. Naming it beats dropping it silently — the model can then say the
      // page was not legible instead of inventing what the image showed.
      if (block.type === "image") {
        return "[image omitted — this model cannot see images]";
      }
      if (block.type === "tool_result") {
        const result = block as { content?: LLMBlock[]; structuredContent?: unknown };
        return result.structuredContent
          ? JSON.stringify(result.structuredContent)
          : blocksToText(result.content ?? []);
      }
      return "";
    })
    .filter(Boolean)
    .join("\n");
}

/**
 * Stagehand v4 has no `baseURL` option: the five built-in providers are reached
 * by name, and everything else — Groq included — goes through this callback,
 * which owns the transport entirely. See `lib/stagehand.ts` for the wiring.
 */
export async function groqGenerate(params: {
  messages: { role: "user" | "assistant"; content: LLMBlock | LLMBlock[] }[];
  systemPrompt?: string;
  temperature?: number;
  stopSequences?: string[];
  responseFormat?: { type: "text" } | { type: "json_schema"; name: string; schema: unknown };
}) {
  const openai = createAIClient();
  const structured = params.responseFormat?.type === "json_schema";

  const messages = [
    ...(params.systemPrompt
      ? [{ role: "system" as const, content: params.systemPrompt }]
      : []),
    ...params.messages.map((message) => ({
      role: message.role,
      content: blocksToText(message.content),
    })),
  ];

  const response = await openai.chat.completions.create({
    model: AI_MODEL,
    messages,
    temperature: params.temperature ?? 0.3,
    max_completion_tokens: AI_MAX_COMPLETION_TOKENS_BROWSER,
    ...(params.stopSequences?.length ? { stop: params.stopSequences } : {}),
    ...(structured
      ? {
          // `strict: false` deliberately: these schemas are generated by
          // Stagehand from our Zod shapes, not by us, so they need not satisfy
          // Groq's strict-mode rules (every key required, no extra properties).
          // A rejected schema is a 400 for the whole page, which is worse than
          // a loosely constrained answer we validate ourselves.
          response_format: {
            type: "json_schema" as const,
            json_schema: {
              name: (params.responseFormat as { name: string }).name,
              schema: (params.responseFormat as { schema: Record<string, unknown> })
                .schema,
              strict: false,
            },
          },
        }
      : {}),
  });

  const text = response.choices[0]?.message?.content ?? "";

  if (!structured) {
    return {
      role: "assistant" as const,
      content: { type: "text" as const, text },
      outputFormat: "text" as const,
    };
  }

  return {
    role: "assistant" as const,
    content: { type: "text" as const, text },
    outputFormat: "json_schema" as const,
    structuredContent: JSON.parse(text),
  };
}
